### PR TITLE
Add NOTEs marking inaccuracies in the text.

### PR DESCRIPTION
**Pull request by mraleph**
(I am using PR mechanism because it is easier to place my comments right next to the text this way). The PR should not be merged obviously.

### CODE REVIEW

**Comment by mraleph** [comment]
@vandadnp

**Comment by vandadnp** [comment]
thank you so very very much @mraleph for taking the time to point out my mistakes
I will go through your comments and send a PR to fix those issues, I'll see then if I can assign you as a reviewer
By any chance would you be interested in being an admin on this repo so you can review PRs?
Thank you once more

**Comment by mraleph** [comment]
Feel free to add me as a collaborator. Would be happy to review your changes!

**Comment by vandadnp** [comment]
@mraleph I sent a PR here to address your comments. Could you please have a look:

https://github.com/vandadnp/going-deep-with-dart/pull/5

could you please have a look whenever you have the time? Much appreciated

**Pull request closed without merging**
